kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: factorio-data
  namespace: factorio
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 0.5Gi
