apiVersion: v1
kind: Service
metadata:
  name: factorio-server-udp
  namespace: factorio
  labels:
    app: factorio-server
    app.kubernetes.io/name: factorio-server
    app.kubernetes.io/instance: factorio-000
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: gameserver
    app.kubernetes.io/part-of: factorio-server
    app.kubernetes.io/managed-by: manual
spec:
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 34197 # Expose 34197
    targetPort: 34197
  selector:
    app: factorio-server
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-server-tcp
  namespace: factorio
  labels:
    app: factorio-server
    app.kubernetes.io/name: factorio-server
    app.kubernetes.io/instance: factorio-000
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: gameserver
    app.kubernetes.io/part-of: factorio-server
    app.kubernetes.io/managed-by: manual
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 27015 # Expose 27015
    targetPort: 27015
  selector:
    app: factorio-server
